table 'Planta Ppto'
	lineageTag: 6dd4c21c-3b50-42b3-9017-e7b44bde6e90

	measure Ind_Rot = (SUM('Planta Ppto'[Ingresos])-SUM('Planta Ppto'[Retiros]))/sum('Planta Ppto'[Total-Sena])
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: Medidas
		lineageTag: 19650ba2-b55d-4486-b176-fac7bc1c9a97

		changedProperty = IsHidden

	measure Resumen = SUM('Planta Ppto'[Total])
		formatString: 0
		displayFolder: Medidas
		lineageTag: 4cd9619f-5262-441f-8f78-8c1cce817be9

		changedProperty = IsHidden

	measure tot_Año_prom =
			
			VAR MesSel = MAX ( 'Planta Ppto'[Mes Num] )
			RETURN
			DIVIDE(
			    CALCULATE(
			        [Resumen],
			        FILTER(
			            ALL ( 'Planta Ppto'[Mes Num] ),
			            'Planta Ppto'[Mes Num] <= MesSel
			        )
			    ),
			    CALCULATE(
			        DISTINCTCOUNT ( 'Planta Ppto'[Mes Num] ),
			        FILTER(
			            ALL ( 'Planta Ppto'[Mes Num] ),
			            'Planta Ppto'[Mes Num] <= MesSel
			        )
			    )
			)
		formatString: #,0.00
		displayFolder: Medidas
		lineageTag: 5f68c1c5-9b09-4ea7-ae36-ac0712edba0c

		changedProperty = IsHidden

	measure Var_Ppto =
			
			VAR Ppto2025 =
			    CALCULATE(
			        [tot_Año_prom],
			        'Planta Ppto'[Ppto/Real] = "Ppto",
			        'Planta Ppto'[Año] = "2025"
			    )
			VAR Ppto2024 =
			    CALCULATE(
			        [tot_Año_prom],
			        'Planta Ppto'[Ppto/Real] = "Ppto",
			        'Planta Ppto'[Año] = "2024"
			    )
			RETURN
			DIVIDE( Ppto2025, Ppto2024 ) - 1
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: Medidas
		lineageTag: eb629bb9-c65d-42b3-ad0f-b3f59547e6b4

		changedProperty = IsHidden

	measure Var_Real =
			( CALCULATE([tot_Año_prom],'Planta Ppto'[Ppto/Real]="Real",'Planta Ppto'[Año]="2025")/
			CALCULATE([tot_Año_prom],'Planta Ppto'[Ppto/Real]="Real",'Planta Ppto'[Año]="2024"))-1
		formatString: 0\ %;-0\ %;0\ %
		displayFolder: Medidas
		lineageTag: c87924ea-9a2d-40d9-acd1-3f11a6210689

		changedProperty = IsHidden

	measure Tot_Indef = SUM('Planta Ppto'[Indefinidos])
		formatString: #,0
		displayFolder: Medidas
		lineageTag: cc6613f5-63a4-4990-9ddb-1036fe164982

		changedProperty = IsHidden

	measure tot_Año_Indef_Prom =
			VAR MesSel = MAX ( 'Planta Ppto'[Mes Num] )
			RETURN
			DIVIDE(
			    CALCULATE(
			        [Tot_Indef],
			        FILTER(
			            ALL ( 'Planta Ppto'[Mes Num] ),
			            'Planta Ppto'[Mes Num] <= MesSel
			        )
			    ),
			    CALCULATE(
			        DISTINCTCOUNT ( 'Planta Ppto'[Mes Num] ),
			        FILTER(
			            ALL ( 'Planta Ppto'[Mes Num] ),
			            'Planta Ppto'[Mes Num] <= MesSel
			        )
			    )
			)
		formatString: #,0
		displayFolder: Medidas
		lineageTag: 5596a837-44d4-4cc4-84e8-61fc597d691b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Tot_Fijo = SUM('Planta Ppto'[Fijos])
		formatString: 0
		displayFolder: Medidas
		lineageTag: 44ba6019-39f7-4227-827c-3ad221f3bc3a

		changedProperty = IsHidden

	measure tot_Año_Fijo_Prom =
			VAR MesSel = MAX ( 'Planta Ppto'[Mes Num] )
			RETURN
			DIVIDE(
			    CALCULATE(
			        [Tot_Fijo],
			        FILTER(
			            ALL ( 'Planta Ppto'[Mes Num] ),
			            'Planta Ppto'[Mes Num] <= MesSel
			        )
			    ),
			    CALCULATE(
			        DISTINCTCOUNT ( 'Planta Ppto'[Mes Num] ),
			        FILTER(
			            ALL ( 'Planta Ppto'[Mes Num] ),
			            'Planta Ppto'[Mes Num] <= MesSel
			        )
			    )
			)
		displayFolder: Medidas
		lineageTag: 31fc3985-4b8c-4db0-8495-7604fa20f8c1

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tot_Temp = SUM('Planta Ppto'[Temporales])
		formatString: 0
		displayFolder: Medidas
		lineageTag: 3978f09c-250b-4bef-a1cc-c725741f1f93

		changedProperty = IsHidden

	measure tot_Año_Temp_prom =
			
			VAR MesSel = MAX ( 'Planta Ppto'[Mes Num] )
			RETURN
			DIVIDE(
			    CALCULATE(
			        [Tot_Temp],
			        FILTER(
			            ALL ( 'Planta Ppto'[Mes Num] ),
			            'Planta Ppto'[Mes Num] <= MesSel
			        )
			    ),
			    CALCULATE(
			        DISTINCTCOUNT ( 'Planta Ppto'[Mes Num] ),
			        FILTER(
			            ALL ( 'Planta Ppto'[Mes Num] ),
			            'Planta Ppto'[Mes Num] <= MesSel
			        )
			    )
			)
		displayFolder: Medidas
		lineageTag: d96ff88b-9ffd-4170-99dd-199ce5873478

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tot_Sena = SUM('Planta Ppto'[Sena])
		formatString: 0
		displayFolder: Medidas
		lineageTag: 3abfcbdc-0417-41b3-90c7-fabd7b8f9d5e

		changedProperty = IsHidden

	measure tot_Año_Sena_prom =
			
			VAR MesSel = MAX ( 'Planta Ppto'[Mes Num] )
			RETURN
			DIVIDE(
			    CALCULATE(
			        [Tot_Sena],
			        FILTER(
			            ALL ( 'Planta Ppto'[Mes Num] ),
			            'Planta Ppto'[Mes Num] <= MesSel
			        )
			    ),
			    CALCULATE(
			        DISTINCTCOUNT ( 'Planta Ppto'[Mes Num] ),
			        FILTER(
			            ALL ( 'Planta Ppto'[Mes Num] ),
			            'Planta Ppto'[Mes Num] <= MesSel
			        )
			    )
			)
		formatString: 0
		displayFolder: Medidas
		lineageTag: b55d3010-15a6-415a-bf67-34ce4fad828b

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isDecimal":true}

	measure KPI_PPTO = IF([Var_Ppto]>0,UNICHAR(129093),UNICHAR(129095))
		displayFolder: Medidas
		lineageTag: 7755b6fe-a6d7-43af-b4ba-0e07cc45bef5

	measure KPI_REAL = IF([Var_Real]>0,UNICHAR(129093),UNICHAR(129095))
		displayFolder: Medidas
		lineageTag: c6b06e10-5a17-4c58-bfba-dd8fbe9c0daa

	measure Ind_Retiros = SUM('Planta Ppto'[Retiros])/SUM('Planta Ppto'[Total-Sena])
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Medidas
		lineageTag: 725f6b0b-d70f-4ace-8f20-6772c3ab0771

	measure Efic = SUM('Planta Ppto'[Gasto Personal])/SUM('Planta Ppto'[Ventas (MM)])
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Medidas
		lineageTag: 69cefef4-b72b-45be-9704-9899959d97d3

	measure KPI_EFI = IF([Efic]>[%Efiprom],UNICHAR(129093),UNICHAR(129095))
		displayFolder: Medidas
		lineageTag: 8ae1e81b-f515-4171-88bb-d10e0af2a47d

	measure %Efiprom = SUM('Planta Ppto'[Ppto Gasto Personal])/SUM('Planta Ppto'[Ppto Ventas (MM)])
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Medidas
		lineageTag: f26b1d68-3e6f-4765-ab96-747382975db4

	measure Var_GL = [Efic]/[%Efiprom]
		displayFolder: Medidas
		lineageTag: 18e0fa81-c218-4bcc-a26c-0b8472fa0851

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Tot_Año = [Tot_Fijo]+[Tot_Indef]+[Tot_Temp]+[Tot_Sena]
		formatString: #,0
		displayFolder: Medidas
		lineageTag: ed016dde-f503-47cc-8015-922e7e8dcf1e

	measure Efic_Emp = SUM('Planta Ppto'[Ventas (MM)])/[Tot_Colab-Sena]
		formatString: \$\ #,0.###############;-\$\ #,0.###############;\$\ #,0.###############
		displayFolder: Medidas
		lineageTag: b9286b75-d034-42df-a854-8efb2a6f9eb8

		annotation PBI_FormatHint = {"currencyCulture":"es-CO"}

	measure Prom_Colab = CALCULATE(AVERAGE('Planta Ppto'[Total]),'Planta Ppto'[Ppto/Real]="REAL")
		displayFolder: Medidas
		lineageTag: d6b7e095-8ae8-4eaa-8149-abc607bfa3dc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Prom_Colab_Directo = CALCULATE(AVERAGE('Planta Ppto'[Indefinidos]),'Planta Ppto'[Ppto/Real]="REAL")+CALCULATE(AVERAGE('Planta Ppto'[Fijos]),'Planta Ppto'[Ppto/Real]="REAL")
		displayFolder: Medidas
		lineageTag: 64d4532d-0ba5-49cd-abeb-6ffc4e5a3a7e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Cump_GL = SUM('Planta Ppto'[Gasto Personal])/SUM('Planta Ppto'[Ppto Gasto Personal])
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Medidas
		lineageTag: 83bb187f-5554-47b2-b369-5e438a085377

	measure Prom_Anual_Real =
			
			AVERAGEX(
			    VALUES ( 'Planta Ppto'[Mes Num] ),
			    CALCULATE(
			        SUM ( 'Planta Ppto'[Total] ),
			        'Planta Ppto'[Ppto/Real] = "Real"
			    )
			)
		displayFolder: Medidas
		lineageTag: 2e80dc1b-e3af-41f2-98a5-6d64e66b110c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Prom_Anual_Real_Linea =
			
			IF(
			    SELECTEDVALUE('Planta Ppto'[Ppto/Real]) = "Real",
			    [Prom_Anual_Real],
			    BLANK()
			)
		displayFolder: Medidas
		lineageTag: 4b842184-799a-4e58-8616-3735afb8bfa5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Prom_Anual_Real_Indef =
			
			AVERAGEX(
			    VALUES ( 'Planta Ppto'[Mes Num] ),
			    CALCULATE(
			        SUM ( 'Planta Ppto'[Indefinidos] ),
			        'Planta Ppto'[Ppto/Real] = "Real"
			    )
			)
		displayFolder: Medidas
		lineageTag: 5de4c5e3-c916-4b84-be98-8fb39c159d2d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Prom_Anual_Real_Sena =
			
			AVERAGEX(
			    VALUES ( 'Planta Ppto'[Mes Num] ),
			    CALCULATE(
			        SUM ( 'Planta Ppto'[Sena] ),
			        'Planta Ppto'[Ppto/Real] = "Real"
			    )
			)
		displayFolder: Medidas
		lineageTag: aa54cfbc-0fde-46a5-863d-481dd9d078a1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Prom_Anual_Real_Temp =
			
			AVERAGEX(
			    VALUES ( 'Planta Ppto'[Mes Num] ),
			    CALCULATE(
			        SUM ( 'Planta Ppto'[Temporales] ),
			        'Planta Ppto'[Ppto/Real] = "Real"
			    )
			)
		displayFolder: Medidas
		lineageTag: 0df6bb92-1d04-418f-a02d-6fa92448faa3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Prom_Anual_Real_Fijo =
			
			AVERAGEX(
			    VALUES ( 'Planta Ppto'[Mes Num] ),
			    CALCULATE(
			        SUM ( 'Planta Ppto'[Fijos] ),
			        'Planta Ppto'[Ppto/Real] = "Real"
			    )
			)
		displayFolder: Medidas
		lineageTag: fbba9119-b3b1-452f-8025-d4dfb9e5bbdc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure tot_Año_Indef_PromEmpresas_FIX =
			
			VAR MesSel = MAX ( 'Planta Ppto'[Mes Num] )
			
			-- Promedio YTD consolidado (suma de empresas seleccionadas / #meses YTD)
			VAR NumYTD_Total =
			    CALCULATE(
			        [Tot_Indef],
			        FILTER( ALL('Planta Ppto'[Mes Num]), 'Planta Ppto'[Mes Num] <= MesSel )
			    )
			
			VAR DenYTD_Total =
			    CALCULATE(
			        DISTINCTCOUNT('Planta Ppto'[Mes Num]),
			        FILTER( ALL('Planta Ppto'[Mes Num]), 'Planta Ppto'[Mes Num] <= MesSel )
			    )
			
			VAR PromYTD_Total = DIVIDE( NumYTD_Total, DenYTD_Total )
			
			-- Promedio YTD por empresa (para cuando estás en el nivel Empresa)
			VAR PromYTD_PorEmpresa =
			    AVERAGEX(
			        VALUES ( 'Planta Ppto'[Empresa] ),
			        VAR NumYTD_Emp =
			            CALCULATE(
			                [Tot_Indef],
			                FILTER( ALL('Planta Ppto'[Mes Num]), 'Planta Ppto'[Mes Num] <= MesSel )
			            )
			        VAR DenYTD_Emp =
			            CALCULATE(
			                DISTINCTCOUNT('Planta Ppto'[Mes Num]),
			                FILTER( ALL('Planta Ppto'[Mes Num]), 'Planta Ppto'[Mes Num] <= MesSel )
			            )
			        RETURN DIVIDE( NumYTD_Emp, DenYTD_Emp )
			    )
			
			RETURN
			IF(
			    ISINSCOPE('Planta Ppto'[Empresa]),   -- Si estoy en fila Empresa
			    PromYTD_PorEmpresa,                  -- muestro promedio por empresa
			    PromYTD_Total                        -- si es total, muestro consolidado
			)
		displayFolder: Medidas
		lineageTag: df1e2e0b-fc91-493e-a82f-989ef99867ed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure tot_Año_Fijo_PromEmpresas_FIX = ```
			
			VAR MesSel = MAX ( 'Planta Ppto'[Mes Num] )
			
			VAR NumYTD_Total =
			    CALCULATE(
			        [Tot_Fijo],
			        FILTER( ALL('Planta Ppto'[Mes Num]), 'Planta Ppto'[Mes Num] <= MesSel )
			    )
			
			VAR DenYTD_Total =
			    CALCULATE(
			        DISTINCTCOUNT('Planta Ppto'[Mes Num]),
			        FILTER( ALL('Planta Ppto'[Mes Num]), 'Planta Ppto'[Mes Num] <= MesSel )
			    )
			
			VAR PromYTD_Total = DIVIDE( NumYTD_Total, DenYTD_Total )
			
			VAR PromYTD_PorEmpresa =
			    AVERAGEX(
			        VALUES ( 'Planta Ppto'[Empresa] ),
			        VAR NumYTD =
			            CALCULATE(
			                [Tot_Fijo],
			                FILTER( ALL('Planta Ppto'[Mes Num]), 'Planta Ppto'[Mes Num] <= MesSel )
			            )
			        VAR DenYTD =
			            CALCULATE(
			                DISTINCTCOUNT('Planta Ppto'[Mes Num]),
			                FILTER( ALL('Planta Ppto'[Mes Num]), 'Planta Ppto'[Mes Num] <= MesSel )
			            )
			        RETURN DIVIDE( NumYTD, DenYTD )
			    )
			
			RETURN
			IF(
			    ISINSCOPE('Planta Ppto'[Empresa]),
			    PromYTD_PorEmpresa,
			    PromYTD_Total
			)
			
			```
		displayFolder: Medidas
		lineageTag: e9190bab-e36f-4b75-a611-32e4bca03d83

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure tot_Año_Sena_PromEmpresas_FIX = ```
			
			VAR MesSel = MAX ( 'Planta Ppto'[Mes Num] )
			
			VAR NumYTD_Total =
			    CALCULATE(
			        [Tot_Sena],
			        FILTER( ALL('Planta Ppto'[Mes Num]), 'Planta Ppto'[Mes Num] <= MesSel )
			    )
			
			VAR DenYTD_Total =
			    CALCULATE(
			        DISTINCTCOUNT('Planta Ppto'[Mes Num]),
			        FILTER( ALL('Planta Ppto'[Mes Num]), 'Planta Ppto'[Mes Num] <= MesSel )
			    )
			
			VAR PromYTD_Total = DIVIDE( NumYTD_Total, DenYTD_Total )
			
			VAR PromYTD_PorEmpresa =
			    AVERAGEX(
			        VALUES ( 'Planta Ppto'[Empresa] ),
			        VAR NumYTD =
			            CALCULATE(
			                [Tot_Sena],
			                FILTER( ALL('Planta Ppto'[Mes Num]), 'Planta Ppto'[Mes Num] <= MesSel )
			            )
			        VAR DenYTD =
			            CALCULATE(
			                DISTINCTCOUNT('Planta Ppto'[Mes Num]),
			                FILTER( ALL('Planta Ppto'[Mes Num]), 'Planta Ppto'[Mes Num] <= MesSel )
			            )
			        RETURN DIVIDE( NumYTD, DenYTD )
			    )
			
			RETURN
			IF(
			    ISINSCOPE('Planta Ppto'[Empresa]),
			    PromYTD_PorEmpresa,
			    PromYTD_Total
			)
			
			```
		displayFolder: Medidas
		lineageTag: 29336c6c-82e0-4a74-94e8-26522a15125d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure tot_Año_Temp_PromEmpresas_FIX =
			
			VAR MesSel = MAX ( 'Planta Ppto'[Mes Num] )
			
			VAR NumYTD_Total =
			    CALCULATE(
			        [Tot_Temp],
			        FILTER( ALL('Planta Ppto'[Mes Num]), 'Planta Ppto'[Mes Num] <= MesSel )
			    )
			
			VAR DenYTD_Total =
			    CALCULATE(
			        DISTINCTCOUNT('Planta Ppto'[Mes Num]),
			        FILTER( ALL('Planta Ppto'[Mes Num]), 'Planta Ppto'[Mes Num] <= MesSel )
			    )
			
			VAR PromYTD_Total = DIVIDE( NumYTD_Total, DenYTD_Total )
			
			VAR PromYTD_PorEmpresa =
			    AVERAGEX(
			        VALUES ( 'Planta Ppto'[Empresa] ),
			        VAR NumYTD =
			            CALCULATE(
			                [Tot_Temp],
			                FILTER( ALL('Planta Ppto'[Mes Num]), 'Planta Ppto'[Mes Num] <= MesSel )
			            )
			        VAR DenYTD =
			            CALCULATE(
			                DISTINCTCOUNT('Planta Ppto'[Mes Num]),
			                FILTER( ALL('Planta Ppto'[Mes Num]), 'Planta Ppto'[Mes Num] <= MesSel )
			            )
			        RETURN DIVIDE( NumYTD, DenYTD )
			    )
			
			RETURN
			IF(
			    ISINSCOPE('Planta Ppto'[Empresa]),
			    PromYTD_PorEmpresa,
			    PromYTD_Total
			)
		displayFolder: Medidas
		lineageTag: 12e304b4-e6f0-47bc-8f34-3210e8679dd8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total-Sena YTD Año Seleccionado' =
			
			VAR AnioSel = SELECTEDVALUE('DimPeriodoYM'[Año])
			VAR MesMax = MAX('DimPeriodoYM'[Numero])
			RETURN
			IF(
			    OR(ISBLANK(AnioSel), ISBLANK(MesMax)),
			    BLANK(),
			    CALCULATE(
			        [SumadeTotal-Sena],
			        'DimPeriodoYM'[Año] = AnioSel,
			        FILTER(ALL('DimPeriodoYM'[Numero]), 'DimPeriodoYM'[Numero] <= MesMax)
			    )
			)
		formatString: 0
		displayFolder: Medidas
		lineageTag: 0c692bb4-192f-44d8-980e-8f4f516bb564

	measure SumadeTotal-Sena = SUM('Planta Ppto'[Total-Sena])
		formatString: 0
		displayFolder: Medidas
		lineageTag: 1a509881-f952-4bd8-91a5-6d4d158220ce

	measure PromediodeTotal-Sena =
			
			AVERAGEX (
			    VALUES ( DimPeriodoYM[IndexAnioMes] ),
			    CALCULATE ( [SumadeTotal-Sena] )
			)
		displayFolder: Medidas
		lineageTag: 31d3f86c-eb09-4667-872f-48d9ca92d68b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ppto/Real
		dataType: string
		lineageTag: 680bd1cc-a163-48d3-a00e-c207cef4c544
		summarizeBy: none
		sourceColumn: Ppto/Real

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Año
		dataType: string
		lineageTag: ab96c98a-19e5-4161-83ca-831c2e1bf7ec
		summarizeBy: none
		sourceColumn: Año

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 48216664-d7db-4dd8-99c7-d4a5b0995d4b
		summarizeBy: none
		sourceColumn: Mes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Grupo Empresa'
		dataType: string
		lineageTag: efd7e754-e540-4a4d-b578-1856f96ceb8b
		summarizeBy: none
		sourceColumn: Grupo Empresa

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Empresa
		dataType: string
		lineageTag: 31887a71-84b5-4475-bf17-24622c5096b8
		summarizeBy: none
		sourceColumn: Empresa

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Fijos
		dataType: int64
		formatString: 0
		lineageTag: 9b120369-318c-41e6-9e06-5eb037fb61a3
		summarizeBy: sum
		sourceColumn: Fijos

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Indefinidos
		dataType: int64
		formatString: 0
		lineageTag: 187aea24-83df-4dbc-b4a3-e44b73f34db3
		summarizeBy: sum
		sourceColumn: Indefinidos

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Sena
		dataType: int64
		formatString: 0
		lineageTag: 8cc404e6-148a-4509-807c-69cc62542fd6
		summarizeBy: sum
		sourceColumn: Sena

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Temporales
		dataType: int64
		formatString: 0
		lineageTag: caa0a696-8f6b-4433-9279-934ced33ab0e
		summarizeBy: sum
		sourceColumn: Temporales

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Total
		dataType: int64
		formatString: 0
		lineageTag: a43a91ad-aafd-4680-807e-d3bee49cb8b5
		summarizeBy: sum
		sourceColumn: Total

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Total-Sena
		dataType: int64
		formatString: #,0
		lineageTag: 7f58b44e-a933-40b8-ab31-fb4df3b8a70c
		summarizeBy: sum
		sourceColumn: Total-Sena

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Ingresos
		dataType: int64
		formatString: 0
		lineageTag: cb9765c4-fa3c-4554-b041-0af3efe00390
		summarizeBy: sum
		sourceColumn: Ingresos

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Retiros
		dataType: int64
		formatString: 0
		lineageTag: 9cc61043-f235-44e1-bcb7-6660dedc6e3e
		summarizeBy: sum
		sourceColumn: Retiros

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Mes Num'
		dataType: string
		lineageTag: 710825fe-1f6e-41e7-abc7-7d4a1dc4c0c9
		summarizeBy: none
		sourceColumn: Mes Num

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Ventas (MM)'
		dataType: decimal
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a75b1f99-6eb4-4860-a70c-6e669035fa19
		summarizeBy: sum
		sourceColumn: Ventas (MM)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	column 'Gasto Personal'
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: fa0bfd12-d47e-48bf-81fa-d8ff2e53d100
		summarizeBy: sum
		sourceColumn: Gasto Personal

		annotation SummarizationSetBy = Automatic

	column 'Ppto Ventas (MM)'
		dataType: decimal
		formatString: \$\ #,0.###############;-\$\ #,0.###############;\$\ #,0.###############
		lineageTag: c8b4338e-fb4b-49b0-a1c0-bf25e3a40602
		summarizeBy: sum
		sourceColumn: Ppto Ventas (MM)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-CO"}

	column 'Ppto Gasto Personal'
		dataType: decimal
		formatString: \$\ #,0.###############;-\$\ #,0.###############;\$\ #,0.###############
		lineageTag: 1fcda0ec-aca1-45c0-88c8-eb3d1927d061
		summarizeBy: sum
		sourceColumn: Ppto Gasto Personal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-CO"}

	column Column20
		dataType: string
		lineageTag: c2caed1e-36b1-470c-b1fe-72419ba0d0b1
		summarizeBy: none
		sourceColumn: Column20

		annotation SummarizationSetBy = Automatic

	column IndexAnioMes =
			
			'Planta Ppto'[Año] * 12 + 'Planta Ppto'[Mes Num]
		lineageTag: a5aafd95-e37d-4b91-adf1-4c06c5e18b5b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ingresos-Temporal
		dataType: string
		lineageTag: 3ab0f27b-70f6-4f3d-870d-75ace206579e
		summarizeBy: none
		sourceColumn: Ingresos-Temporal

		annotation SummarizationSetBy = Automatic

	partition 'Planta Ppto' = m
		mode: import
		queryGroup: PptovsReal
		source =
				let
				    Origen = Excel.Workbook(Web.Contents("https://lemcosas-my.sharepoint.com/personal/edwin_clavijo_challenger_co/Documents/Documentos/Anal%C3%ADtica%20del%20Grupo%20Empresarial%20Lemco/03_Fuentes_Datos/01_Talento_Humano/02_HeadCount/PptovsReal.xlsx"), null, true),
				    #"Planta Personal_Sheet" = Origen{[Item="Planta Personal",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Planta Personal_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Fijos", Int64.Type}, {"Indefinidos", Int64.Type}, {"Sena", Int64.Type}, {"Temporales", Int64.Type}, {"Total", Int64.Type}, {"Total-Sena", Int64.Type}, {"Ingresos", Int64.Type}, {"Retiros", Int64.Type}, {"Ventas (MM)", Currency.Type}, {"Gasto Personal", Currency.Type}, {"Ppto Ventas (MM)", Currency.Type}, {"Ppto Gasto Personal", Currency.Type}})
				in
				    #"Tipo cambiado"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

