table 'Planta Ppto'
	lineageTag: 6dd4c21c-3b50-42b3-9017-e7b44bde6e90

	column Ppto/Real
		dataType: string
		lineageTag: 680bd1cc-a163-48d3-a00e-c207cef4c544
		summarizeBy: none
		sourceColumn: Ppto/Real

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Año
		dataType: string
		lineageTag: ab96c98a-19e5-4161-83ca-831c2e1bf7ec
		summarizeBy: none
		sourceColumn: Año

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 48216664-d7db-4dd8-99c7-d4a5b0995d4b
		summarizeBy: none
		sourceColumn: Mes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Grupo Empresa'
		dataType: string
		lineageTag: efd7e754-e540-4a4d-b578-1856f96ceb8b
		summarizeBy: none
		sourceColumn: Grupo Empresa

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Empresa
		dataType: string
		lineageTag: 31887a71-84b5-4475-bf17-24622c5096b8
		summarizeBy: none
		sourceColumn: Empresa

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Fijos
		dataType: int64
		formatString: 0
		lineageTag: 9b120369-318c-41e6-9e06-5eb037fb61a3
		summarizeBy: sum
		sourceColumn: Fijos

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Indefinidos
		dataType: int64
		formatString: 0
		lineageTag: 187aea24-83df-4dbc-b4a3-e44b73f34db3
		summarizeBy: sum
		sourceColumn: Indefinidos

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Sena
		dataType: int64
		formatString: 0
		lineageTag: 8cc404e6-148a-4509-807c-69cc62542fd6
		summarizeBy: sum
		sourceColumn: Sena

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Temporales
		dataType: int64
		formatString: 0
		lineageTag: caa0a696-8f6b-4433-9279-934ced33ab0e
		summarizeBy: sum
		sourceColumn: Temporales

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Total
		dataType: int64
		formatString: 0
		lineageTag: a43a91ad-aafd-4680-807e-d3bee49cb8b5
		summarizeBy: sum
		sourceColumn: Total

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Total-Sena
		dataType: int64
		formatString: #,0
		lineageTag: 7f58b44e-a933-40b8-ab31-fb4df3b8a70c
		summarizeBy: sum
		sourceColumn: Total-Sena

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Ingresos
		dataType: int64
		formatString: 0
		lineageTag: cb9765c4-fa3c-4554-b041-0af3efe00390
		summarizeBy: sum
		sourceColumn: Ingresos

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Retiros
		dataType: int64
		formatString: 0
		lineageTag: 9cc61043-f235-44e1-bcb7-6660dedc6e3e
		summarizeBy: sum
		sourceColumn: Retiros

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Mes Num'
		dataType: string
		lineageTag: 710825fe-1f6e-41e7-abc7-7d4a1dc4c0c9
		summarizeBy: none
		sourceColumn: Mes Num

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Ventas (MM)'
		dataType: decimal
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a75b1f99-6eb4-4860-a70c-6e669035fa19
		summarizeBy: sum
		sourceColumn: Ventas (MM)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	column 'Gasto Personal'
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: fa0bfd12-d47e-48bf-81fa-d8ff2e53d100
		summarizeBy: sum
		sourceColumn: Gasto Personal

		annotation SummarizationSetBy = Automatic

	column 'Ppto Ventas (MM)'
		dataType: decimal
		formatString: \$\ #,0.###############;-\$\ #,0.###############;\$\ #,0.###############
		lineageTag: c8b4338e-fb4b-49b0-a1c0-bf25e3a40602
		summarizeBy: sum
		sourceColumn: Ppto Ventas (MM)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-CO"}

	column 'Ppto Gasto Personal'
		dataType: decimal
		formatString: \$\ #,0.###############;-\$\ #,0.###############;\$\ #,0.###############
		lineageTag: 1fcda0ec-aca1-45c0-88c8-eb3d1927d061
		summarizeBy: sum
		sourceColumn: Ppto Gasto Personal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-CO"}

	column IndexAnioMes =
			
			'Planta Ppto'[Año] * 12 + 'Planta Ppto'[Mes Num]
		lineageTag: a5aafd95-e37d-4b91-adf1-4c06c5e18b5b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ingresos-Temporal
		dataType: string
		lineageTag: 3ab0f27b-70f6-4f3d-870d-75ace206579e
		summarizeBy: none
		sourceColumn: Ingresos-Temporal

		annotation SummarizationSetBy = Automatic

	column 'Retiros Voluntarios'
		dataType: int64
		formatString: 0
		lineageTag: 1651f88d-405e-4dca-b8d1-52b0a303f785
		summarizeBy: sum
		sourceColumn: Retiros Voluntarios

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Column21
		dataType: string
		lineageTag: 2f267484-7b53-45fe-ad63-a9b8cd6c4af3
		summarizeBy: none
		sourceColumn: Column21

		annotation SummarizationSetBy = Automatic

	partition 'Planta Ppto' = m
		mode: import
		queryGroup: PptovsReal
		source =
				let
				    Origen = Excel.Workbook(Web.Contents("https://lemcosas-my.sharepoint.com/personal/edwin_clavijo_challenger_co/Documents/Documentos/Anal%C3%ADtica%20del%20Grupo%20Empresarial%20Lemco/03_Fuentes_Datos/01_Talento_Humano/02_HeadCount/PptovsReal.xlsx"), null, true),
				    #"Planta Personal_Sheet" = Origen{[Item="Planta Personal",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Planta Personal_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Fijos", Int64.Type}, {"Indefinidos", Int64.Type}, {"Sena", Int64.Type}, {"Temporales", Int64.Type}, {"Total", Int64.Type}, {"Total-Sena", Int64.Type}, {"Ingresos", Int64.Type}, {"Retiros", Int64.Type}, {"Retiros Voluntarios", Int64.Type}, {"Ventas (MM)", Currency.Type}, {"Gasto Personal", Currency.Type}, {"Ppto Ventas (MM)", Currency.Type}, {"Ppto Gasto Personal", Currency.Type}})
				in
				    #"Tipo cambiado"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

